### ISSUE TITLE
Errors when my friend hit zombies

### ISSUE THREAD

**Issue by Taargard** [hypnotoadtrance/MoreTraits#173]
I encountered a strange error. While I'm playing alone on my server, they don't appear. When a friend connected to me, he began to receive errors associated with this mod and the dynamic dialogue mod every time he hit a zombie.
Please help :3

`attempted index: PackMouseDynamic of non-table: null
function: MTDTraitsGainsByLevel -- file: MoreTraits - Dynamic.lua line # 94 | MOD: More Traits - Dynamic Traits
function: MTDInitializeEvents -- file: MoreTraits - Dynamic.lua line # 784 | MOD: More Traits - Dynamic Traits
java.lang.RuntimeException: attempted index: PackMouseDynamic of non-table: null
    at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:492)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
    at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
    at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
    at zombie.Lua.Event.trigger(Event.java:64)
    at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:65)
    at zombie.gameStates.IngameState.enter(IngameState.java:737)
    at zombie.gameStates.GameStateMachine.update(GameStateMachine.java:145)
    at zombie.GameWindow.logic(GameWindow.java:298)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.GameWindow.frameStep(GameWindow.java:765)
    at zombie.GameWindow.run_ez(GameWindow.java:667)
    at zombie.GameWindow.mainThread(GameWindow.java:495)
    at java.base/java.lang.Thread.run(Unknown Source)
`

`attempted index: 1.0 of non-table: null
function: WeaponCheck -- file: DMMainFile.lua line # 466 | MOD: Dynamic Monologue
java.lang.RuntimeException: attempted index: 1.0 of non-table: null
    at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:492)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
    at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
    at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
    at zombie.Lua.Event.trigger(Event.java:64)
    at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:134)
    at zombie.characters.IsoGameCharacter.setPrimaryHandItem(IsoGameCharacter.java:2959)
    at zombie.network.GameClient.receiveEquip(GameClient.java:3897)
    at zombie.network.PacketTypes$PacketType.onMainLoopHandlePacketInternal(PacketTypes.java:1028)
    at zombie.network.GameClient.mainLoopHandlePacketInternal(GameClient.java:644)
    at zombie.network.GameClient.mainLoopDealWithNetData(GameClient.java:621)
    at zombie.network.GameClient.update(GameClient.java:431)
    at zombie.gameStates.IngameState.enter(IngameState.java:756)
    at zombie.gameStates.GameStateMachine.update(GameStateMachine.java:145)
    at zombie.GameWindow.logic(GameWindow.java:298)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.GameWindow.frameStep(GameWindow.java:765)
    at zombie.GameWindow.run_ez(GameWindow.java:667)
    at zombie.GameWindow.mainThread(GameWindow.java:495)
    at java.base/java.lang.Thread.run(Unknown Source)
`

`attempted index: UnwaveringDynamic of non-table: null
function: MTDTraitGainsByInjuries -- file: MoreTraits - Dynamic.lua line # 687 | MOD: More Traits - Dynamic Traits
function: MTDEveryTenMinutesMain -- file: MoreTraits - Dynamic.lua line # 24 | MOD: More Traits - Dynamic Traits
java.lang.RuntimeException: attempted index: UnwaveringDynamic of non-table: null
    at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:492)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
    at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
    at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
    at zombie.Lua.Event.trigger(Event.java:64)
    at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:65)
    at zombie.GameTime.update(GameTime.java:671)
    at zombie.gameStates.IngameState.UpdateStuff(IngameState.java:566)
    at zombie.gameStates.IngameState.updateInternal(IngameState.java:1623)
    at zombie.gameStates.IngameState.update(IngameState.java:1333)
    at zombie.gameStates.GameStateMachine.update(GameStateMachine.java:101)
    at zombie.GameWindow.logic(GameWindow.java:298)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.GameWindow.frameStep(GameWindow.java:765)
    at zombie.GameWindow.run_ez(GameWindow.java:667)
    at zombie.GameWindow.mainThread(GameWindow.java:495)
    at java.base/java.lang.Thread.run(Unknown Source)
`

`attempted index: LeadFootDynamic of non-table: null
function: MTDOnWeaponHitCharacterMain -- file: MoreTraits - Dynamic.lua line # 34 | MOD: More Traits - Dynamic Traits
java.lang.RuntimeException: attempted index: LeadFootDynamic of non-table: null
    at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:492)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
    at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
    at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
    at zombie.Lua.Event.trigger(Event.java:64)
    at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:214)
    at zombie.characters.IsoGameCharacter.Hit(IsoGameCharacter.java:6424)
    at zombie.characters.IsoZombie.Hit(IsoZombie.java:928)
    at zombie.characters.IsoGameCharacter.Hit(IsoGameCharacter.java:6398)
    at zombie.ai.states.SwipeStatePlayer.ConnectSwing(SwipeStatePlayer.java:2097)
    at zombie.ai.states.SwipeStatePlayer.animEvent(SwipeStatePlayer.java:392)
    at zombie.ai.StateMachine.lambda$stateAnimEvent$6(StateMachine.java:268)
    at zombie.util.lambda.Consumers$Params2$CallbackStackItem.accept(Consumers.java:93)
    at zombie.util.list.PZArrayUtil.forEach(PZArrayUtil.java:904)
    at zombie.util.Lambda.lambda$forEachFrom$3(Lambda.java:219)
    at zombie.util.lambda.Stacks$Params5$CallbackStackItem.invoke(Stacks.java:345)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:142)
    at zombie.util.Lambda.forEachFrom(Lambda.java:216)
    at zombie.ai.StateMachine.stateAnimEvent(StateMachine.java:264)
    at zombie.characters.IsoGameCharacter.OnAnimEvent(IsoGameCharacter.java:4235)
    at zombie.characters.IsoPlayer.OnAnimEvent(IsoPlayer.java:9401)
    at zombie.core.skinnedmodel.advancedanimation.AdvancedAnimator.OnAnimEvent(AdvancedAnimator.java:264)
    at zombie.core.skinnedmodel.advancedanimation.AnimLayer.invokeAnimEvent(AnimLayer.java:211)
    at zombie.core.skinnedmodel.advancedanimation.AnimLayer.updateInternal(AnimLayer.java:419)
    at zombie.GameProfiler.invokeAndMeasure(GameProfiler.java:166)
    at zombie.core.skinnedmodel.advancedanimation.AnimLayer.Update(AnimLayer.java:323)
    at zombie.core.skinnedmodel.advancedanimation.AdvancedAnimator$SubLayerSlot.update(AdvancedAnimator.java:665)
    at zombie.core.skinnedmodel.advancedanimation.AdvancedAnimator.updateInternal(AdvancedAnimator.java:403)
    at zombie.GameProfiler.invokeAndMeasure(GameProfiler.java:166)
    at zombie.core.skinnedmodel.advancedanimation.AdvancedAnimator.update(AdvancedAnimator.java:368)
    at zombie.characters.IsoGameCharacter.postUpdateInternal(IsoGameCharacter.java:12087)
    at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
    at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:130)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
    at zombie.characters.IsoGameCharacter.postupdate(IsoGameCharacter.java:12063)
    at zombie.characters.IsoPlayer.postupdateInternal(IsoPlayer.java:3740)
    at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
    at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:130)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
    at zombie.characters.IsoPlayer.postupdate(IsoPlayer.java:3733)
    at zombie.MovingObjectUpdateSchedulerUpdateBucket.postupdate(MovingObjectUpdateSchedulerUpdateBucket.java:97)
    at zombie.MovingObjectUpdateScheduler.postupdate(MovingObjectUpdateScheduler.java:168)
    at zombie.CollisionManager.resolveContactsInternal(CollisionManager.java:411)
    at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
    at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:130)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
    at zombie.CollisionManager.ResolveContacts(CollisionManager.java:236)
    at zombie.iso.IsoWorld.updateInternal(IsoWorld.java:2638)
    at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
    at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
    at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
    at zombie.util.Lambda.capture(Lambda.java:130)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
    at zombie.iso.IsoWorld.update(IsoWorld.java:2568)
    at zombie.gameStates.IngameState.updateInternal(IngameState.java:1617)
    at zombie.gameStates.IngameState.update(IngameState.java:1333)
    at zombie.gameStates.GameStateMachine.update(GameStateMachine.java:101)
    at zombie.GameWindow.logic(GameWindow.java:298)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.GameWindow.frameStep(GameWindow.java:765)
    at zombie.GameWindow.run_ez(GameWindow.java:667)
    at zombie.GameWindow.mainThread(GameWindow.java:495)
    at java.base/java.lang.Thread.run(Unknown Source)
`

**Comment by hypnotoadtrance** [comment]
Hello,

This appears to be an issue with the More Traits - Dynamic submod. which is primarily maintained by MusicManiac.

I will refer your issue to them for response.

Thank you

**Comment by MusicManiac** [comment]
For some reason game doesn't see mod sandbox variables, I have no idea why, nor I know how to resolve it. Try the usual uninstall-reinstall shenanigans.

**Comment by Taargard** [comment]
Well... for comparison, I tried installing [this ](https://steamcommunity.com/sharedfiles/filedetails/?id=2068698366&searchtext=more+traits)version of the mod, which, as far as I understand, is several updates behind the current (your) version... and the error disappeared.
